spring.application.name=medic
spring.profiles.active=${SPRING_PROFILE}
jwt.secret-key=${JWT_SECRET}
jwt.expiration-time=${JWT_EXPIRATION}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.upload.base-dir=uploads
springdoc.swagger-ui.persist-authorization=true
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.web.error.include-stacktrace=never
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
logging.level.com.ga.medic=WARN
springdoc.show-actuator=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
spring.devtools.restart.enabled=false