spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.web.error.include-stacktrace=always
spring.jpa.hibernate.ddl-auto=create
logging.level.root=INFO
logging.level.com.ga.medic=DEBUG
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true